---
namespace: jewdba
name: eda
version: 1.0.0
readme: README.md
authors:
  - jewdba <https://github.com/jewdba>
description: >
  Event-Driven Ansible (EDA) plugin to tail Oracle Automatic Diagnostic Repository (ADR) XML logfile
  and emit structured events based on regex pattern matching.
license: "MIT"
license_file: LICENSE
tags:
  - ansible-eda
  - oracle
  - event-source
  - automation
dependencies: {}
repository: "https://github.com/jewdba/oracle_adr_alertmanager"
documentation: "https://github.com/jewdba/oracle_adr_alertmanager#readme"
homepage: "https://github.com/jewdba/oracle_adr_alertmanager"
issues: "https://github.com/jewdba/oracle_adr_alertmanager/issues"

# Exclude these patterns from the collection build artifact
build_ignore:
  # Editor / OS files
  - ".DS_Store"
  # Cache, venvs, Python artifacts
  - ".venv"
  - "__pycache__"
  - "*.egg-info"
  - ".pytest_cache"
  - ".mypy_cache"
  - ".ruff_cache"
  # Tests / tooling
  - "tests"
  - "package.json"
  - "pyproject.toml"
  - "uv.lock"
  # IDE / CIs
  - "build_docsite"
  - "build"
  - ".gitignore"
  - ".github"
  - ".vscode"
  - ".pre-commit-config.yaml"
  # Misc
  - "CONTRIBUTING.md"
