name: "Python setup with uv (cached)"
description: "Setup Python, cache deps, install uv, sync project dependencies"

inputs:
  python-version:
    description: "Python version"
    default: "3.12"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    # Cache uv's global cache (wheels + downloads)
    - name: Cache uv
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/uv
        key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ inputs.python-version }}-

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash

    - name: Install uv
      run: pip install uv
      shell: bash

    - name: Sync dependencies
      run: uv sync --all-extras
      shell: bash
