name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & uv
        uses: ./.github/actions/python-setup
        with:
          python-version: "3.11"

      - name: Run Pylint
        run: uv run pylint plugins

      - name: Run unit & integration tests
        run: uv run pytest

      - name: Run Ansible sanity tests
        run: uv run ansible-test sanity

      - name: Run Ansible unit tests
        run: uv run ansible-test units --python 3.11
