name: "Python setup with uv"
description: "Setup Python, install uv, and sync dependencies"

inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash

    - name: Install uv
      run: pip install uv
      shell: bash

    - name: Sync dependencies
      run: uv sync --all-extras
      shell: bash
