name: Python setup
description: "Set up Python, create uv virtual environment, and install all dependencies"

inputs:
  python-version:
    description: "Python version to use"
    required: true

outputs:
  python-path:
    description: "Path to the Python executable"
    value: ${{ steps.python-path.outputs.python-path }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install uv
      run: python -m pip install uv

    - name: Create virtual environment
      shell: bash
      run: |
        uv venv --clear

    - name: Install all project dependencies
      shell: bash
      run: |
        uv sync --all-extras

    - name: Set Python path output
      id: python-path
      shell: bash
      run: echo "python-path=$(which python)" >> "$GITHUB_OUTPUT"
