name: Python setup
description: "Set up Python, create uv virtual environment, and install all dependencies"

inputs:
  python-version:
    description: "Python version to use"
    required: true

outputs:
  python-path:
    description: "Path to the Python executable"
    value: ${{ steps.python-path.outputs.python-path }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash

    - name: Install uv
      run: python -m pip install uv
      shell: bash

    - name: Create virtual environment
      run: |
        uv venv --clear
      shell: bash

    - name: Install all project dependencies
      run: |
        uv sync --all-extras
      shell: bash

    - name: Set Python path output
      id: python-path
      run: echo "python-path=$(which python)" >> "$GITHUB_OUTPUT"
      shell: bash
